version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    networks:
      - valeVision
      - networkMysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev -- --host 0.0.0.0 --port 5174
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
    ports:
      - "5174:5174"
    depends_on:
      - backend
    networks:
      - valeVision

networks:
  valeVision:
    driver: bridge

  networkMysql:
    external: true
    name: mysql_networkMysql